// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/logpipeline.proto

package logpipeline

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TelemetryRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdSerial      string                 `protobuf:"bytes,1,opt,name=id_serial,json=idSerial,proto3" json:"id_serial,omitempty"`
	Fecha         string                 `protobuf:"bytes,2,opt,name=fecha,proto3" json:"fecha,omitempty"`
	Hora          string                 `protobuf:"bytes,3,opt,name=hora,proto3" json:"hora,omitempty"`
	Data          string                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"` // JSON serializado
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryRecord) Reset() {
	*x = TelemetryRecord{}
	mi := &file_proto_logpipeline_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryRecord) ProtoMessage() {}

func (x *TelemetryRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logpipeline_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryRecord.ProtoReflect.Descriptor instead.
func (*TelemetryRecord) Descriptor() ([]byte, []int) {
	return file_proto_logpipeline_proto_rawDescGZIP(), []int{0}
}

func (x *TelemetryRecord) GetIdSerial() string {
	if x != nil {
		return x.IdSerial
	}
	return ""
}

func (x *TelemetryRecord) GetFecha() string {
	if x != nil {
		return x.Fecha
	}
	return ""
}

func (x *TelemetryRecord) GetHora() string {
	if x != nil {
		return x.Hora
	}
	return ""
}

func (x *TelemetryRecord) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type SendRecordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*TelemetryRecord     `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRecordsRequest) Reset() {
	*x = SendRecordsRequest{}
	mi := &file_proto_logpipeline_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRecordsRequest) ProtoMessage() {}

func (x *SendRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logpipeline_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRecordsRequest.ProtoReflect.Descriptor instead.
func (*SendRecordsRequest) Descriptor() ([]byte, []int) {
	return file_proto_logpipeline_proto_rawDescGZIP(), []int{1}
}

func (x *SendRecordsRequest) GetRecords() []*TelemetryRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *SendRecordsRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type SendRecordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Inserted      int32                  `protobuf:"varint,2,opt,name=inserted,proto3" json:"inserted,omitempty"`
	Duplicates    int32                  `protobuf:"varint,3,opt,name=duplicates,proto3" json:"duplicates,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRecordsResponse) Reset() {
	*x = SendRecordsResponse{}
	mi := &file_proto_logpipeline_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRecordsResponse) ProtoMessage() {}

func (x *SendRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logpipeline_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRecordsResponse.ProtoReflect.Descriptor instead.
func (*SendRecordsResponse) Descriptor() ([]byte, []int) {
	return file_proto_logpipeline_proto_rawDescGZIP(), []int{2}
}

func (x *SendRecordsResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SendRecordsResponse) GetInserted() int32 {
	if x != nil {
		return x.Inserted
	}
	return 0
}

func (x *SendRecordsResponse) GetDuplicates() int32 {
	if x != nil {
		return x.Duplicates
	}
	return 0
}

func (x *SendRecordsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_logpipeline_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logpipeline_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_logpipeline_proto_rawDescGZIP(), []int{3}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_logpipeline_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logpipeline_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_logpipeline_proto_rawDescGZIP(), []int{4}
}

func (x *PingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_logpipeline_proto protoreflect.FileDescriptor

const file_proto_logpipeline_proto_rawDesc = "" +
	"\n" +
	"\x17proto/logpipeline.proto\x12\vlogpipeline\"l\n" +
	"\x0fTelemetryRecord\x12\x1b\n" +
	"\tid_serial\x18\x01 \x01(\tR\bidSerial\x12\x14\n" +
	"\x05fecha\x18\x02 \x01(\tR\x05fecha\x12\x12\n" +
	"\x04hora\x18\x03 \x01(\tR\x04hora\x12\x12\n" +
	"\x04data\x18\x04 \x01(\tR\x04data\"h\n" +
	"\x12SendRecordsRequest\x126\n" +
	"\arecords\x18\x01 \x03(\v2\x1c.logpipeline.TelemetryRecordR\arecords\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\"{\n" +
	"\x13SendRecordsResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1a\n" +
	"\binserted\x18\x02 \x01(\x05R\binserted\x12\x1e\n" +
	"\n" +
	"duplicates\x18\x03 \x01(\x05R\n" +
	"duplicates\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\r\n" +
	"\vPingRequest\"&\n" +
	"\fPingResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\x9d\x01\n" +
	"\fLogIngestion\x12P\n" +
	"\vSendRecords\x12\x1f.logpipeline.SendRecordsRequest\x1a .logpipeline.SendRecordsResponse\x12;\n" +
	"\x04Ping\x12\x18.logpipeline.PingRequest\x1a\x19.logpipeline.PingResponseB!Z\x1fgrpc-pipeline/proto;logpipelineb\x06proto3"

var (
	file_proto_logpipeline_proto_rawDescOnce sync.Once
	file_proto_logpipeline_proto_rawDescData []byte
)

func file_proto_logpipeline_proto_rawDescGZIP() []byte {
	file_proto_logpipeline_proto_rawDescOnce.Do(func() {
		file_proto_logpipeline_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_logpipeline_proto_rawDesc), len(file_proto_logpipeline_proto_rawDesc)))
	})
	return file_proto_logpipeline_proto_rawDescData
}

var file_proto_logpipeline_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_logpipeline_proto_goTypes = []any{
	(*TelemetryRecord)(nil),     // 0: logpipeline.TelemetryRecord
	(*SendRecordsRequest)(nil),  // 1: logpipeline.SendRecordsRequest
	(*SendRecordsResponse)(nil), // 2: logpipeline.SendRecordsResponse
	(*PingRequest)(nil),         // 3: logpipeline.PingRequest
	(*PingResponse)(nil),        // 4: logpipeline.PingResponse
}
var file_proto_logpipeline_proto_depIdxs = []int32{
	0, // 0: logpipeline.SendRecordsRequest.records:type_name -> logpipeline.TelemetryRecord
	1, // 1: logpipeline.LogIngestion.SendRecords:input_type -> logpipeline.SendRecordsRequest
	3, // 2: logpipeline.LogIngestion.Ping:input_type -> logpipeline.PingRequest
	2, // 3: logpipeline.LogIngestion.SendRecords:output_type -> logpipeline.SendRecordsResponse
	4, // 4: logpipeline.LogIngestion.Ping:output_type -> logpipeline.PingResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_logpipeline_proto_init() }
func file_proto_logpipeline_proto_init() {
	if File_proto_logpipeline_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_logpipeline_proto_rawDesc), len(file_proto_logpipeline_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_logpipeline_proto_goTypes,
		DependencyIndexes: file_proto_logpipeline_proto_depIdxs,
		MessageInfos:      file_proto_logpipeline_proto_msgTypes,
	}.Build()
	File_proto_logpipeline_proto = out.File
	file_proto_logpipeline_proto_goTypes = nil
	file_proto_logpipeline_proto_depIdxs = nil
}
